name: CI
on: [ push, pull_request ]
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # TODO (spencer): possibly fail if this condition is not met.
      - name: Check for ZDNS License Header
        run: |
          export NO_HEADERS_FOUND=$(grep -RiL --include="*.go" "ZDNS Copyright .* Regents of the University of Michigan" ./)
          if test -n "$NO_HEADERS_FOUND"; then
            echo 'FOUND .go FILES WITHOUT HEADERS.'
            echo "$NO_HEADERS_FOUND"
          else
            echo 'All .go files in repo have an appropriate header'
          fi
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build
        run: |
          go version
          make
      - name: Unit Tests
        run: go test -v ./...
      - name: Integration Tests
        run: |
          sudo rm /etc/resolv.conf
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          python --version
          ./integration_tests.py
