name: CI
on:
  push:
    branches:
      - master
      - feature/add-versioning
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build
        run: |
          go version
          go build ./...
          cd zdns
          go build
      - name: Unit Tests
        run: go test -v ./...
      - name: Integration Tests
        run: |
          sudo rm /etc/resolv.conf
          sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
          python --version
          ./integration_tests.py

  # Only tag releases off the master branch: these checks are strictly needed
  # but are useful in case we start building off other branches in the future
  release:
    if: ${{ github.ref == 'refs/heads/feature/add-versioning' }}
    needs: build-and-test
    name: Release Next Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.17.x ]
    steps:
    - name: Release Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: feature/add-versioning
        dry_run: true
